name: Update README

on: push

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Modify README file
        run: |
          echo "Updated by GitHub Actions on $(date)" >> README.md  # Пример модификации файла

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"
          git add README.md
          git commit -m "Update README.md with new content"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}